import React, { useState } from 'react'
import { Database, Copy, Check, Terminal, Eye, EyeOff, Wifi, WifiOff, Loader2 } from 'lucide-react'
import { getSupabaseClient, saveSupabaseConfig } from '../utils/supabaseClient'
import { useToast } from '../components/Toast'

export default function SupabaseSetupTab({ onReconnect }) {
  const toast = useToast()
  const [copiedSql, setCopiedSql] = useState(false)
  const [showKey, setShowKey] = useState(false)
  const [testingConnection, setTestingConnection] = useState(false)

  const savedUrl = localStorage.getItem('SUPABASE_PROJECT_URL') || 'https://ksnkiylrqdfvebeacpeg.supabase.co'
  const savedKey = localStorage.getItem('SUPABASE_ANON_KEY') || 'sb_publishable_s7XEfFey0yAYntiDsnhI-A_o4Mke27b'

  const [formUrl, setFormUrl] = useState(savedUrl)
  const [formKey, setFormKey] = useState(savedKey)

  const sqlSchema = `-- ============================================================
-- SUPABASE / POSTGRESQL DATABASE SCHEMA FOR RESTAURANT PAYROLL
-- Remote License Verification & Telemetry Radar Script
-- ============================================================

-- 1. Create Devices & Licenses Table
CREATE TABLE IF NOT EXISTS public.licenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hardware_id TEXT UNIQUE NOT NULL,
    restaurant_name TEXT NOT NULL,
    owner_name TEXT,
    phone TEXT,
    expiry_date DATE NOT NULL DEFAULT (CURRENT_DATE + INTERVAL '1 year'),
    kill_switch BOOLEAN NOT NULL DEFAULT FALSE,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'active',
    employees_count INT DEFAULT 0,
    drivers_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Telemetry Pings Stream Table
CREATE TABLE IF NOT EXISTS public.telemetry_pings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hardware_id TEXT NOT NULL,
    employees_count INT DEFAULT 0,
    drivers_count INT DEFAULT 0,
    platform TEXT,
    hostname TEXT,
    app_version TEXT,
    kill_switch BOOLEAN DEFAULT FALSE,
    revoked BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Remote Updates Table (OTA Targeted Updates)
CREATE TABLE IF NOT EXISTS public.updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version TEXT NOT NULL,
    target_hardware_id TEXT NOT NULL DEFAULT '*',
    target_name TEXT NOT NULL DEFAULT 'جميع المطاعم',
    download_url TEXT NOT NULL,
    mandatory BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure missing columns exist in updates & telemetry_pings
ALTER TABLE public.updates ADD COLUMN IF NOT EXISTS target_name TEXT DEFAULT 'جميع المطاعم';
ALTER TABLE public.updates ADD COLUMN IF NOT EXISTS mandatory BOOLEAN DEFAULT FALSE;
ALTER TABLE public.updates ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.updates ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';

ALTER TABLE public.telemetry_pings ADD COLUMN IF NOT EXISTS update_available BOOLEAN DEFAULT FALSE;
ALTER TABLE public.telemetry_pings ADD COLUMN IF NOT EXISTS target_version TEXT;
ALTER TABLE public.telemetry_pings ADD COLUMN IF NOT EXISTS update_title TEXT;
ALTER TABLE public.telemetry_pings ADD COLUMN IF NOT EXISTS release_notes TEXT;
ALTER TABLE public.telemetry_pings ADD COLUMN IF NOT EXISTS update_url TEXT;
ALTER TABLE public.telemetry_pings ADD COLUMN IF NOT EXISTS mandatory BOOLEAN DEFAULT FALSE;
ALTER TABLE public.telemetry_pings ADD COLUMN IF NOT EXISTS target_hardware_id TEXT;

-- 4. Auto Kill Switch, Device Registration & OTA Update Trigger on Telemetry Ping
CREATE OR REPLACE FUNCTION public.process_telemetry_ping()
RETURNS TRIGGER AS $$
DECLARE
    device_record RECORD;
    global_kill RECORD;
    latest_update RECORD;
BEGIN
    -- A) Check Global Kill Switch FIRST (hardware_id = '*')
    SELECT kill_switch, revoked INTO global_kill
    FROM public.licenses
    WHERE hardware_id = '*';

    IF FOUND AND (global_kill.kill_switch = TRUE OR global_kill.revoked = TRUE) THEN
        NEW.kill_switch := TRUE;
        NEW.revoked := TRUE;
        RETURN NEW;
    END IF;

    -- B) Check specific hardware_id
    SELECT kill_switch, revoked, expiry_date INTO device_record
    FROM public.licenses
    WHERE UPPER(hardware_id) = UPPER(NEW.hardware_id);

    IF FOUND THEN
        NEW.kill_switch := device_record.kill_switch;
        NEW.revoked := device_record.revoked;
    ELSE
        -- C) Auto-register unlisted device so it re-appears in Licenses tab immediately!
        INSERT INTO public.licenses (hardware_id, restaurant_name, status)
        VALUES (UPPER(NEW.hardware_id), COALESCE('مطعم (' || SUBSTRING(NEW.hardware_id FROM 1 FOR 8) || ')', NEW.hardware_id), 'active')
        ON CONFLICT (hardware_id) DO NOTHING;
    END IF;

    -- D) Check for Active Targeted OTA Updates
    SELECT version, download_url, notes, mandatory, target_hardware_id INTO latest_update
    FROM public.updates
    WHERE status = 'active'
      AND (target_hardware_id = '*' OR UPPER(target_hardware_id) = UPPER(NEW.hardware_id))
    ORDER BY created_at DESC
    LIMIT 1;

    IF FOUND THEN
        NEW.update_available := TRUE;
        NEW.target_version := latest_update.version;
        NEW.update_url := latest_update.download_url;
        NEW.release_notes := latest_update.notes;
        NEW.mandatory := latest_update.mandatory;
        NEW.target_hardware_id := latest_update.target_hardware_id;
        NEW.update_title := 'تحديث نظام جديد v' || latest_update.version;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER on_telemetry_ping_insert
    BEFORE INSERT ON public.telemetry_pings
    FOR EACH ROW
    EXECUTE FUNCTION public.process_telemetry_ping();

-- 5. Enable Row Level Security
ALTER TABLE public.licenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_pings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.updates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public all licenses" ON public.licenses;
DROP POLICY IF EXISTS "Allow public all telemetry_pings" ON public.telemetry_pings;
DROP POLICY IF EXISTS "Allow public all updates" ON public.updates;

CREATE POLICY "Allow public all licenses" ON public.licenses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all telemetry_pings" ON public.telemetry_pings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all updates" ON public.updates FOR ALL USING (true) WITH CHECK (true);

-- 5b. One-Time License Delivery Tokens Table
CREATE TABLE IF NOT EXISTS public.license_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token TEXT UNIQUE NOT NULL,
    license_key TEXT NOT NULL,
    hardware_id TEXT NOT NULL,
    restaurant_name TEXT NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    used_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.license_tokens ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all license_tokens" ON public.license_tokens;
CREATE POLICY "Allow public all license_tokens" ON public.license_tokens FOR ALL USING (true) WITH CHECK (true);

-- 6. Storage Bucket for Update Files
INSERT INTO storage.buckets (id, name, public) VALUES ('updates', 'updates', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Read Updates Bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public Upload Updates Bucket" ON storage.objects;
CREATE POLICY "Public Read Updates Bucket" ON storage.objects FOR SELECT USING (bucket_id = 'updates');
CREATE POLICY "Public Upload Updates Bucket" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'updates');

-- 7. Reset / Wipe Database (Run this to clear all data):
-- TRUNCATE public.licenses, public.telemetry_pings, public.license_tokens CASCADE;`

  const handleCopySql = () => {
    navigator.clipboard.writeText(sqlSchema)
    setCopiedSql(true)
    toast.success('تم نسخ سكربت SQL إلى الحافظة')
    setTimeout(() => setCopiedSql(false), 2500)
  }

  const handleTestConnection = async () => {
    setTestingConnection(true)
    try {
      const client = getSupabaseClient()
      if (!client) {
        toast.error('لا يمكن إنشاء اتصال — تحقق من رابط المشروع')
        return
      }
      const { error } = await client.from('licenses').select('id').limit(1)
      if (error) {
        toast.error('فشل الاتصال: ' + error.message)
      } else {
        toast.success('الاتصال بـ Supabase ناجح! الجداول متاحة وتعمل')
      }
    } catch (err) {
      toast.error('خطأ بالاتصال: ' + err.message)
    } finally {
      setTestingConnection(false)
    }
  }

  const handleSaveConfig = (e) => {
    e.preventDefault()
    saveSupabaseConfig(formUrl, formKey)
    toast.success('تم حفظ بيانات الربط بنجاح! يتم الاتصال بالمشروع الجديد...')
    setTimeout(() => {
      if (onReconnect) onReconnect()
    }, 500)
  }

  return (
    <div className="space-y-6">
      {/* Title Header */}
      <div className="bg-[#0c1427] p-6 rounded-2xl border border-slate-800/80 shadow-sm">
        <div className="flex items-center gap-4">
          <div className="w-11 h-11 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-400 flex items-center justify-center shrink-0">
            <Database className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-white">إعداد قواعد البيانات (Supabase Integration)</h2>
            <p className="text-xs text-slate-400 mt-0.5">
              مخطط SQL الكامل لإنشاء الجداول وإعداد الـ Trigger التلقائي
            </p>
          </div>
        </div>
      </div>

      {/* Connection Settings */}
      <div className="bg-[#0c1427] p-6 rounded-2xl border border-slate-800/80 space-y-4">
        <h3 className="text-xs font-bold text-white flex items-center gap-2 border-b border-slate-800/80 pb-3">
          <Wifi className="w-4 h-4 text-emerald-400" />
          <span>بيانات الربط بـ Supabase (Project Credentials)</span>
        </h3>

        <form onSubmit={handleSaveConfig} className="space-y-4 text-xs">
          <div>
            <label className="block text-slate-300 font-semibold mb-1.5">رابط المشروع (Project URL)</label>
            <input
              type="url"
              value={formUrl}
              onChange={(e) => setFormUrl(e.target.value)}
              placeholder="https://your-project-id.supabase.co"
              className="w-full bg-slate-900 border border-slate-700/80 rounded-xl px-3.5 py-2.5 text-slate-200 font-mono focus:border-blue-500 focus:outline-none transition dir-ltr"
              required
            />
          </div>

          <div>
            <label className="block text-slate-300 font-semibold mb-1.5">المفتاح العام (Anon Key)</label>
            <div className="relative">
              <input
                type={showKey ? 'text' : 'password'}
                value={formKey}
                onChange={(e) => setFormKey(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700/80 rounded-xl px-3.5 py-2.5 text-slate-200 font-mono focus:border-blue-500 focus:outline-none transition dir-ltr pe-10"
                required
              />
              <button
                type="button"
                onClick={() => setShowKey(!showKey)}
                className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-200 transition"
              >
                {showKey ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
            </div>
          </div>

          <div className="flex gap-3 pt-1">
            <button
              type="submit"
              className="flex-1 py-2.5 bg-blue-600 hover:bg-blue-500 text-white font-semibold rounded-xl transition"
            >
              حفظ وربط لوحة التحكم
            </button>
            <button
              type="button"
              onClick={handleTestConnection}
              disabled={testingConnection}
              className="px-5 py-2.5 bg-slate-900 border border-slate-700/80 hover:bg-slate-800 text-slate-300 font-semibold rounded-xl transition flex items-center gap-2 disabled:opacity-50"
            >
              {testingConnection ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Wifi className="w-4 h-4" />
              )}
              <span>اختبار الاتصال</span>
            </button>
          </div>
        </form>
      </div>

      {/* SQL Script */}
      <div className="bg-[#0c1427] p-6 rounded-2xl border border-slate-800/80 space-y-4">
        <div className="flex justify-between items-center border-b border-slate-800/80 pb-3">
          <h3 className="text-xs font-bold text-white flex items-center gap-2">
            <Terminal className="w-4 h-4 text-emerald-400" />
            <span>سكربت إنشاء الجداول (PostgreSQL Schema)</span>
          </h3>
          <button
            onClick={handleCopySql}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-semibold transition flex items-center gap-1.5"
          >
            {copiedSql ? (
              <><Check className="w-4 h-4 text-emerald-300" /><span>تم النسخ!</span></>
            ) : (
              <><Copy className="w-4 h-4" /><span>نسخ SQL</span></>
            )}
          </button>
        </div>

        <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 font-mono text-xs text-emerald-300/80 leading-relaxed overflow-x-auto max-h-[420px] dir-ltr select-all">
          <pre className="whitespace-pre">{sqlSchema}</pre>
        </div>

        <div className="p-3 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-300 text-[11px] font-medium">
          الخطوات: انسخ هذا السكربت ← افتح Supabase Dashboard ← اذهب لـ SQL Editor ← الصق وشغّل
        </div>
      </div>
    </div>
  )
}

